/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cafe;

import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import javax.persistence.*;
import javax.swing.JFileChooser;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author LENOVO
 */
public class Cafe extends javax.swing.JFrame {

    /**
     * Creates new form Cafe
     */
    public Cafe() {
        initComponents();
        tampilData1();
        tampilData2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertDialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        tid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        dsubmt = new javax.swing.JButton();
        tha = new javax.swing.JTextField();
        cbka = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        UpdateDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        tid1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tnama1 = new javax.swing.JTextField();
        dupdate = new javax.swing.JButton();
        tha1 = new javax.swing.JTextField();
        cbka1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        DeleteDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        tid2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tnama2 = new javax.swing.JTextField();
        dya = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        dtidak = new javax.swing.JButton();
        cbka2 = new javax.swing.JComboBox<>();
        tha2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        InsertDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        tid3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tnama3 = new javax.swing.JTextField();
        dsubmit1 = new javax.swing.JButton();
        tjumlah3 = new javax.swing.JTextField();
        tmen3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        UpdateDialog1 = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        tid4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tnama4 = new javax.swing.JTextField();
        dupdate1 = new javax.swing.JButton();
        tjumlah4 = new javax.swing.JTextField();
        tmen4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        DeleteDialog1 = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        tid5 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        tnama5 = new javax.swing.JTextField();
        dya1 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        dtidak1 = new javax.swing.JButton();
        tjumlah5 = new javax.swing.JTextField();
        tmen5 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtab1 = new javax.swing.JTable();
        binsert1 = new javax.swing.JButton();
        bupdate1 = new javax.swing.JButton();
        bdelete1 = new javax.swing.JButton();
        bcetak1 = new javax.swing.JButton();
        bupload1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtab2 = new javax.swing.JTable();
        binsert2 = new javax.swing.JButton();
        bupload2 = new javax.swing.JButton();
        bcetak2 = new javax.swing.JButton();
        bdelete2 = new javax.swing.JButton();
        bupdate2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 33, 146, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Menu");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Menu");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kategori");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));
        jPanel4.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, 146, -1));

        dsubmt.setBackground(new java.awt.Color(204, 204, 255));
        dsubmt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dsubmt.setText("Submit");
        dsubmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsubmtActionPerformed(evt);
            }
        });
        jPanel4.add(dsubmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        jPanel4.add(tha, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, 146, -1));

        cbka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Snack", "Minuman" }));
        jPanel4.add(cbka, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 153, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        javax.swing.GroupLayout InsertDialogLayout = new javax.swing.GroupLayout(InsertDialog.getContentPane());
        InsertDialog.getContentPane().setLayout(InsertDialogLayout);
        InsertDialogLayout.setHorizontalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InsertDialogLayout.setVerticalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid1.setEnabled(false);
        jPanel6.add(tid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 33, 146, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID Menu");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nama Menu");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Harga");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Kategori");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));
        jPanel6.add(tnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 73, 146, -1));

        dupdate.setBackground(new java.awt.Color(204, 204, 255));
        dupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dupdate.setText("Update");
        dupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupdateActionPerformed(evt);
            }
        });
        jPanel6.add(dupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        jPanel6.add(tha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, 146, -1));

        cbka1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Snack" }));
        jPanel6.add(cbka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 153, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        javax.swing.GroupLayout UpdateDialogLayout = new javax.swing.GroupLayout(UpdateDialog.getContentPane());
        UpdateDialog.getContentPane().setLayout(UpdateDialogLayout);
        UpdateDialogLayout.setHorizontalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        UpdateDialogLayout.setVerticalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid2.setEnabled(false);
        jPanel8.add(tid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 146, -1));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ID Menu");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nama Menu");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Harga");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Kategori");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        tnama2.setEnabled(false);
        jPanel8.add(tnama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 146, -1));

        dya.setBackground(new java.awt.Color(204, 204, 255));
        dya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dya.setText("Ya");
        dya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyaActionPerformed(evt);
            }
        });
        jPanel8.add(dya, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 60, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("APAKAH YAKIN INGIN MENGHAPUS DATA INI ?");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        dtidak.setBackground(new java.awt.Color(204, 204, 255));
        dtidak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dtidak.setText("Tidak");
        dtidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtidakActionPerformed(evt);
            }
        });
        jPanel8.add(dtidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, -1));

        cbka2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Snack" }));
        cbka2.setEnabled(false);
        jPanel8.add(cbka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 185, -1, -1));

        tha2.setEnabled(false);
        jPanel8.add(tha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 145, 146, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 290));

        javax.swing.GroupLayout DeleteDialogLayout = new javax.swing.GroupLayout(DeleteDialog.getContentPane());
        DeleteDialog.getContentPane().setLayout(DeleteDialogLayout);
        DeleteDialogLayout.setHorizontalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeleteDialogLayout.setVerticalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(tid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Pesanan");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nama Pelanggan");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jumlah Pesanan");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID Menu");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));
        jPanel5.add(tnama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        dsubmit1.setBackground(new java.awt.Color(204, 204, 255));
        dsubmit1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dsubmit1.setText("Submit");
        dsubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsubmit1ActionPerformed(evt);
            }
        });
        jPanel5.add(dsubmit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        jPanel5.add(tjumlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));
        jPanel5.add(tmen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        javax.swing.GroupLayout InsertDialog1Layout = new javax.swing.GroupLayout(InsertDialog1.getContentPane());
        InsertDialog1.getContentPane().setLayout(InsertDialog1Layout);
        InsertDialog1Layout.setHorizontalGroup(
            InsertDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InsertDialog1Layout.setVerticalGroup(
            InsertDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid4.setEnabled(false);
        jPanel7.add(tid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 140, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ID Pesanan");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 38, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nama Pelanggan");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 78, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Jumlah Pesanan");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ID Menu");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 158, -1, -1));

        tnama4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnama4ActionPerformed(evt);
            }
        });
        jPanel7.add(tnama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        dupdate1.setBackground(new java.awt.Color(204, 204, 255));
        dupdate1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dupdate1.setText("Update");
        dupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dupdate1ActionPerformed(evt);
            }
        });
        jPanel7.add(dupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        jPanel7.add(tjumlah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));
        jPanel7.add(tmen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        javax.swing.GroupLayout UpdateDialog1Layout = new javax.swing.GroupLayout(UpdateDialog1.getContentPane());
        UpdateDialog1.getContentPane().setLayout(UpdateDialog1Layout);
        UpdateDialog1Layout.setHorizontalGroup(
            UpdateDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateDialog1Layout.setVerticalGroup(
            UpdateDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid5.setEnabled(false);
        jPanel10.add(tid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("ID Pesanan");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Nama Pelanggan");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Jumlah Pesanan");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("ID Menu");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        tnama5.setEnabled(false);
        jPanel10.add(tnama5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        dya1.setBackground(new java.awt.Color(204, 204, 255));
        dya1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dya1.setText("Ya");
        dya1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dya1ActionPerformed(evt);
            }
        });
        jPanel10.add(dya1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 60, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("APAKAH YAKIN INGIN MENGHAPUS DATA INI ?");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        dtidak1.setBackground(new java.awt.Color(204, 204, 255));
        dtidak1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dtidak1.setText("Tidak");
        dtidak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtidak1ActionPerformed(evt);
            }
        });
        jPanel10.add(dtidak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, -1));

        tjumlah5.setEnabled(false);
        jPanel10.add(tjumlah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));

        tmen5.setEnabled(false);
        jPanel10.add(tmen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 290));

        javax.swing.GroupLayout DeleteDialog1Layout = new javax.swing.GroupLayout(DeleteDialog1.getContentPane());
        DeleteDialog1.getContentPane().setLayout(DeleteDialog1Layout);
        DeleteDialog1Layout.setHorizontalGroup(
            DeleteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DeleteDialog1Layout.setVerticalGroup(
            DeleteDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CAFEKU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtab1.setBackground(new java.awt.Color(204, 204, 204));
        jtab1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Menu", "Nama Menu", "Harga", "Kategori"
            }
        ));
        jtab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtab1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtab1);
        if (jtab1.getColumnModel().getColumnCount() > 0) {
            jtab1.getColumnModel().getColumn(0).setMinWidth(70);
            jtab1.getColumnModel().getColumn(0).setMaxWidth(70);
            jtab1.getColumnModel().getColumn(1).setMinWidth(170);
            jtab1.getColumnModel().getColumn(1).setMaxWidth(170);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 210));

        binsert1.setBackground(new java.awt.Color(204, 204, 204));
        binsert1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        binsert1.setText("Insert");
        binsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binsert1ActionPerformed(evt);
            }
        });
        jPanel2.add(binsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        bupdate1.setBackground(new java.awt.Color(204, 204, 204));
        bupdate1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bupdate1.setText("Update");
        bupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdate1ActionPerformed(evt);
            }
        });
        jPanel2.add(bupdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        bdelete1.setBackground(new java.awt.Color(204, 204, 204));
        bdelete1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bdelete1.setText("Delete");
        bdelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelete1ActionPerformed(evt);
            }
        });
        jPanel2.add(bdelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        bcetak1.setBackground(new java.awt.Color(204, 204, 204));
        bcetak1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bcetak1.setText("Cetak");
        bcetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetak1ActionPerformed(evt);
            }
        });
        jPanel2.add(bcetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        bupload1.setBackground(new java.awt.Color(204, 204, 204));
        bupload1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bupload1.setText("Upload");
        bupload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupload1ActionPerformed(evt);
            }
        });
        jPanel2.add(bupload1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        jTabbedPane1.addTab("Menu", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtab2.setBackground(new java.awt.Color(204, 204, 204));
        jtab2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jtab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pesanan", "Nama Pelanggan", "Jumlah", "ID Menu"
            }
        ));
        jtab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtab2MouseClicked(evt);
            }
        });
        jtab2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jtab2ComponentMoved(evt);
            }
        });
        jScrollPane4.setViewportView(jtab2);
        if (jtab2.getColumnModel().getColumnCount() > 0) {
            jtab2.getColumnModel().getColumn(0).setMinWidth(100);
            jtab2.getColumnModel().getColumn(0).setMaxWidth(100);
            jtab2.getColumnModel().getColumn(1).setMinWidth(150);
            jtab2.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, 210));

        binsert2.setBackground(new java.awt.Color(204, 204, 204));
        binsert2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        binsert2.setText("Insert");
        binsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binsert2ActionPerformed(evt);
            }
        });
        jPanel3.add(binsert2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        bupload2.setBackground(new java.awt.Color(204, 204, 204));
        bupload2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bupload2.setText("Upload");
        bupload2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupload2ActionPerformed(evt);
            }
        });
        jPanel3.add(bupload2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        bcetak2.setBackground(new java.awt.Color(204, 204, 204));
        bcetak2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bcetak2.setText("Cetak");
        bcetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetak2ActionPerformed(evt);
            }
        });
        jPanel3.add(bcetak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        bdelete2.setBackground(new java.awt.Color(204, 204, 204));
        bdelete2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bdelete2.setText("Delete");
        bdelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelete2ActionPerformed(evt);
            }
        });
        jPanel3.add(bdelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        bupdate2.setBackground(new java.awt.Color(204, 204, 204));
        bupdate2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bupdate2.setText("Update");
        bupdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdate2ActionPerformed(evt);
            }
        });
        jPanel3.add(bupdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        jTabbedPane1.addTab("Pesanan", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 71, -1, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cafe/pngtree-small-coffee-shop-with-wooden-tables-and-chairs-image_2523456.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static final String URL = "jdbc:postgresql://localhost:5432/Cafe";
    static final String USER = "postgres"; // ganti sesuai user PostgreSQL
    static final String PASSWORD = "bagus"; // ganti sesuai password PostgreSQL

    public static Connection getConnection() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            System.out.println("Koneksi ke PostgreSQL berhasil!");
        } catch (SQLException e) {
            System.out.println("Koneksi gagal: " + e.getMessage());
        }
        return conn;
    }

    private void clear() {
        tid.setText("");
        tnama.setText("");
        tha.setText("");
        cbka.setSelectedIndex(0);

        tid.setEditable(true);
    }
    
     private void clear1() {
        tid3.setText("");
        tnama3.setText("");
        tjumlah3.setText("");
        tmen3.setText("");

        tid3.setEditable(true);
    }

    private void dsubmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsubmtActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil nilai dari input form
            int id = Integer.parseInt(tid.getText());
            String nama = tnama.getText();
            int harga = Integer.parseInt(tha.getText());
            String kategori = cbka.getSelectedItem().toString();

            // Buat EntityManager
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            // Buat objek Dataminuman dan isi datanya
            Menu data = new Menu();
            data.setIdMenu(id);
            data.setNamaMenu(nama);
            data.setHarga(harga);
            data.setKategori(kategori);

            // Simpan ke database
            em.getTransaction().begin();
            em.persist(data);
            em.getTransaction().commit();

            InsertDialog.setVisible(false);
            tampilData1();
            clear();
            em.close();
            emf.close();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Menu dan Harga harus berupa angka!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan Insert: " + e.getMessage());
        }
    }//GEN-LAST:event_dsubmtActionPerformed

    private void dupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupdateActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tid.getText());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();
            Menu data = em.find(Menu.class, id);

            if (data != null) {
                data.setNamaMenu(tnama1.getText());
                data.setHarga(Integer.parseInt(tha1.getText()));
                data.setKategori(cbka1.getSelectedItem().toString());

                em.merge(data);
                em.getTransaction().commit();

                UpdateDialog.setVisible(false);
                tampilData1();
                clear();
                em.close();
                emf.close();

                JOptionPane.showMessageDialog(this, " Data berhasil diupdate!");
            } else {
                JOptionPane.showMessageDialog(this, " Data tidak ditemukan!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan update: " + e.getMessage());
        }
    }//GEN-LAST:event_dupdateActionPerformed

    private void dyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyaActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tid2.getText());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();
            Menu m = em.find(Menu.class, id);

            if (m != null) {
                try {
                    em.remove(m);
                    em.getTransaction().commit();

                    DeleteDialog.setVisible(false);
                    tampilData1();
                    clear();

                    JOptionPane.showMessageDialog(this,
                            "Data berhasil dihapus!",
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                } catch (RollbackException ex) {
                    // Ambil root cause paling dalam (biasanya PSQLException)
                    Throwable cause = ex;
                    while (cause.getCause() != null) {
                        cause = cause.getCause();
                    }

                    String message = cause.getMessage();

                    // Tangani error FK constraint dari PostgreSQL
                    if (message != null && message.contains("violates foreign key constraint")) {
                        DeleteDialog.setVisible(false);

                        JOptionPane.showMessageDialog(this,
                                "Tidak dapat menghapus data karena masih digunakan di tabel lain",
                                "Gagal Menghapus", JOptionPane.WARNING_MESSAGE);

                    } else {
                        JOptionPane.showMessageDialog(this,
                                "️Terjadi kesalahan saat menghapus: " + message,
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    if (em.getTransaction().isActive()) {
                        em.getTransaction().rollback();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "Data tidak ditemukan!",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }

            em.close();
            emf.close();

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "️Kesalahan input: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_dyaActionPerformed

    private void dtidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtidakActionPerformed
        // TODO add your handling code here:
        DeleteDialog.setVisible(false);
    }//GEN-LAST:event_dtidakActionPerformed

    private void jtab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtab1MouseClicked
        // TODO add your handling code here:
        tid.setText(jtab1.getValueAt(jtab1.getSelectedRow(), 0).toString());
        tnama.setText(jtab1.getValueAt(jtab1.getSelectedRow(), 1).toString());
        tha.setText(jtab1.getValueAt(jtab1.getSelectedRow(), 2).toString());
        cbka.setSelectedItem(jtab1.getValueAt(jtab1.getSelectedRow(), 3).toString());

        tid.setEditable(false);
    }//GEN-LAST:event_jtab1MouseClicked

    private void jtab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtab2MouseClicked
        // TODO add your handling code here:
//        tid.setText(jtab2.getValueAt(jtab2.getSelectedRow(), 0).toString());
//        tnama.setText(jtab.getValueAt(jtab.getSelectedRow(), 1).toString());
//        cbka.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 2).toString());
//        tha.setText(jtab.getValueAt(jtab.getSelectedRow(), 3).toString());
//        cbu.setSelectedItem(jtab.getValueAt(jtab.getSelectedRow(), 4).toString());
//
//        tid.setEditable(false);
    }//GEN-LAST:event_jtab2MouseClicked

    private void binsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binsert2ActionPerformed
        // TODO add your handling code here:
        clear1();
        InsertDialog1.pack(); // atur ulang ukuran sesuai desain
        InsertDialog1.setLocationRelativeTo(this);
        InsertDialog1.setVisible(true);
    }//GEN-LAST:event_binsert2ActionPerformed

    private void binsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binsert1ActionPerformed
        // TODO add your handling code here:
        clear();
        InsertDialog.pack(); // atur ulang ukuran sesuai desain
        InsertDialog.setLocationRelativeTo(this);
        InsertDialog.setVisible(true);
    }//GEN-LAST:event_binsert1ActionPerformed

    private void bupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate1ActionPerformed
        // TODO add your handling code here:
        int row = jtab1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu untuk diupdate!");
            return;
        }

        // Ambil data dari row
        String id = jtab1.getValueAt(row, 0).toString();
        String nama = jtab1.getValueAt(row, 1).toString();
        String harga = jtab1.getValueAt(row, 2).toString();
        String kategori = jtab1.getValueAt(row, 3).toString();

        // Masukkan ke dialog
        tid1.setText(id);
        tid1.setEditable(false); // biasanya ID tidak boleh diubah
        tnama1.setText(nama);
        tha1.setText(harga);
        cbka1.setSelectedItem(kategori);

        UpdateDialog.pack();
        UpdateDialog.setLocationRelativeTo(this);
        UpdateDialog.setVisible(true);
    }//GEN-LAST:event_bupdate1ActionPerformed

    private void bdelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelete1ActionPerformed
        // TODO add your handling code here:
        int row = jtab1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
            return;
        }

        // ambil data dari tabel
        String id = jtab1.getValueAt(row, 0).toString();
        String nama = jtab1.getValueAt(row, 1).toString();
        String harga = jtab1.getValueAt(row, 2).toString();
        String kategori = jtab1.getValueAt(row, 3).toString();

        // tampilkan ke dialog delete
        tid2.setText(id);
        tnama2.setText(nama);
        tha2.setText(harga);
        cbka2.setSelectedItem(kategori);

        // semua field tidak bisa diedit
        tid2.setEditable(false);
        tnama2.setEditable(false);
        tha2.setEditable(false);
        cbka2.setEnabled(false);

        DeleteDialog.pack();
        DeleteDialog.setLocationRelativeTo(this);
        DeleteDialog.setVisible(true);

    }//GEN-LAST:event_bdelete1ActionPerformed

    private void bupload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupload1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            // Ambil koneksi dari persistence.xml
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                em.getTransaction().begin(); // mulai transaksi

                String line;
                int count = 0;

                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) {
                        continue; // lewati baris kosong
                    }
                    String[] data = line.split(";");
                    if (data.length == 4) {
                        try {
                            Menu m = new Menu();
                            m.setIdMenu(Integer.valueOf(data[0].trim()));
                            m.setNamaMenu(data[1].trim());
                            m.setHarga(Integer.parseInt(data[2].trim()));
                            m.setKategori(data[3].trim());

                            em.persist(m); // simpan ke database
                            count++;

                        } catch (NumberFormatException e) {
                            System.out.println("Baris dilewati (angka salah): " + line);
                        }
                    } else {
                        System.out.println("Format salah: " + line);
                    }
                }

                em.getTransaction().commit(); // simpan semua data ke DB
                tampilData1(); // refresh tabel GUI

                JOptionPane.showMessageDialog(this,
                        "Upload berhasil! " + count + " data dimasukkan.",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan saat membaca file: " + e.getMessage());
            } catch (Exception e) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(this, "Kesalahan upload: " + e.getMessage());
            } finally {
                em.close();
                emf.close();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Upload dibatalkan.", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bupload1ActionPerformed

    private void jtab2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtab2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jtab2ComponentMoved

    private void dsubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsubmit1ActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil nilai dari input form
            int id = Integer.parseInt(tid3.getText());
            String nama = tnama3.getText();
            int jumlah = Integer.parseInt(tjumlah3.getText());
            int idMenuInput = Integer.parseInt(tmen3.getText()); // input ID menu

            // Buat EntityManager
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            // Cari objek Menu berdasarkan ID
            Menu menuObj = em.find(Menu.class, idMenuInput);
            if (menuObj == null) {
                JOptionPane.showMessageDialog(this, "Menu dengan ID " + idMenuInput + " tidak ditemukan.");
                return;
            }

            // Buat objek Pesanan dan isi datanya
            Pesanan pesanan = new Pesanan();
            pesanan.setIdPesanan(id);
            pesanan.setNamaPelanggan(nama);
            pesanan.setJumlah(jumlah);
            pesanan.setIdMenu(menuObj); // **set relasi ke Menu**

            // Simpan ke database
            em.getTransaction().begin();
            em.persist(pesanan);
            em.getTransaction().commit();

            InsertDialog1.setVisible(false);
            tampilData2(); // refresh tabel
            clear();
            em.close();
            emf.close();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Pesanan, Jumlah Pesanan, dan ID Menu harus berupa angka!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan Insert: " + e.getMessage());
        }
    }//GEN-LAST:event_dsubmit1ActionPerformed

    private void dupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dupdate1ActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil data dari TextField di dialog
            int idPesanan = Integer.parseInt(tid4.getText().trim());
            String namaPelanggan = tnama4.getText().trim();
            int jumlah = Integer.parseInt(tjumlah4.getText().trim());
            int idMenuInput = Integer.parseInt(tmen4.getText().trim());

            // Validasi field kosong
            if (namaPelanggan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama pelanggan harus diisi!");
                return;
            }

            // Buat EntityManager
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            // Cari objek Pesanan
            Pesanan pesan = em.find(Pesanan.class, idPesanan);
            if (pesan == null) {
                JOptionPane.showMessageDialog(this, "Data Pesanan tidak ditemukan!");
                em.getTransaction().rollback();
                em.close();
                emf.close();
                return;
            }

            // Cari Menu berdasarkan ID input
            Menu menuObj = em.find(Menu.class, idMenuInput);
            if (menuObj == null) {
                JOptionPane.showMessageDialog(this, "Menu dengan ID " + idMenuInput + " tidak ditemukan!");
                em.getTransaction().rollback();
                em.close();
                emf.close();
                return;
            }

            // Update data
            pesan.setNamaPelanggan(namaPelanggan);
            pesan.setJumlah(jumlah);
            pesan.setIdMenu(menuObj);

            em.merge(pesan); // simpan perubahan
            em.getTransaction().commit();
            em.clear(); // pastikan data terbaru terlihat

            // Refresh JTable di GUI utama
            UpdateDialog1.setVisible(false);
            tampilData2();
            UpdateDialog.setVisible(false);
            clear(); // kosongkan field dialog

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");

            em.close();
            emf.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah Pesanan dan ID Menu harus berupa angka!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan update: " + e.getMessage());
        }
    }//GEN-LAST:event_dupdate1ActionPerformed

    private void dya1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dya1ActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(tid5.getText());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();
            Pesanan pesan = em.find(Pesanan.class, id);

            if (pesan != null) {
                em.remove(pesan);
                em.getTransaction().commit();

                DeleteDialog1.setVisible(false);
                tampilData2();
                clear();
                em.close();
                emf.close();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " Error delete: " + e.getMessage());
        }
    }//GEN-LAST:event_dya1ActionPerformed

    private void dtidak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtidak1ActionPerformed
        // TODO add your handling code here:
        DeleteDialog1.setVisible(false);
    }//GEN-LAST:event_dtidak1ActionPerformed

    private void tnama4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnama4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnama4ActionPerformed

    private void bupload2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupload2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            // Buat EntityManagerFactory sekali
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Pertemuan12PU");
            EntityManager em = emf.createEntityManager();

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                em.getTransaction().begin();

                String line;
                int count = 0;

                while ((line = br.readLine()) != null) {
                    line = line.trim();
                    if (line.isEmpty() || line.startsWith("idPesanan")) {
                        continue; // lewati header atau baris kosong
                    }
                    String[] data = line.split(";");
                    if (data.length != 4) {
                        System.out.println("Format salah: " + line);
                        continue;
                    }

                    try {
                        int idPesanan = Integer.parseInt(data[0].trim());
                        String namaPelanggan = data[1].trim();
                        int jumlah = Integer.parseInt(data[2].trim());
                        int idMenu = Integer.parseInt(data[3].trim());

                        // Ambil Menu dari DB
                        Menu menuObj = em.find(Menu.class, idMenu);
                        if (menuObj == null) {
                            System.out.println("Menu dengan ID " + idMenu + " tidak ditemukan, baris dilewati.");
                            continue;
                        }

                        // Buat objek Pesanan
                        Pesanan p = new Pesanan();
                        p.setIdPesanan(idPesanan);
                        p.setNamaPelanggan(namaPelanggan);
                        p.setJumlah(jumlah);
                        p.setIdMenu(menuObj);

                        em.persist(p); // simpan ke database
                        count++;

                    } catch (NumberFormatException e) {
                        System.out.println("Baris dilewati (angka salah): " + line);
                    }
                }

                em.getTransaction().commit();
                em.clear(); // hapus cache persistence
                tampilData2(); // refresh JTable

                JOptionPane.showMessageDialog(this,
                        "Upload berhasil! " + count + " data dimasukkan.",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan saat membaca file: " + e.getMessage());
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
            } catch (Exception e) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(this, "Kesalahan upload: " + e.getMessage());
            } finally {
                em.close();
                emf.close();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Upload dibatalkan.", "Informasi", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_bupload2ActionPerformed

    private void bdelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelete2ActionPerformed
        // TODO add your handling code here:
        int row = jtab2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
            return;
        }

        // ambil data dari tabel
        String id = jtab2.getValueAt(row, 0).toString();
        String nama = jtab2.getValueAt(row, 1).toString();
        String jumlah = jtab2.getValueAt(row, 2).toString();
        String idmenu = jtab2.getValueAt(row, 3).toString();

        // tampilkan ke dialog delete
        tid5.setText(id);
        tnama5.setText(nama);
        tjumlah5.setText(jumlah);
        tmen5.setText(idmenu);

        DeleteDialog1.pack();
        DeleteDialog1.setLocationRelativeTo(this);
        DeleteDialog1.setVisible(true);
    }//GEN-LAST:event_bdelete2ActionPerformed

    private void bupdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate2ActionPerformed
        // TODO add your handling code here:
        int row = jtab2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu untuk diupdate!");
            return;
        }

        // Ambil data dari row
        String id = jtab2.getValueAt(row, 0).toString();
        String nama = jtab2.getValueAt(row, 1).toString();
        String jumlah = jtab2.getValueAt(row, 2).toString();
        String idmenu = jtab2.getValueAt(row, 3).toString();

        // Masukkan ke dialog
        tid4.setText(id);
        tid4.setEditable(false); // biasanya ID tidak boleh diubah
        tnama4.setText(nama);
        tjumlah4.setText(jumlah);
        tmen4.setText(idmenu);

        UpdateDialog1.pack();
        UpdateDialog1.setLocationRelativeTo(this);
        UpdateDialog1.setVisible(true);
    }//GEN-LAST:event_bupdate2ActionPerformed

    private void bcetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetak1ActionPerformed
        // TODO add your handling code here:
        try {
            // Lokasi file laporan .jasper (hasil compile dari .jrxml)
            String reportPath = "src/Cafe/Menu.jasper";
            Connection conn = getConnection();

            net.sf.jasperreports.engine.JasperPrint jp
                    = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportPath, null, conn);

            net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_bcetak1ActionPerformed

    private void bcetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetak2ActionPerformed
        // TODO add your handling code here:
        try {
            // Lokasi file laporan .jasper (hasil compile dari .jrxml)
            String reportPath = "src/Cafe/Pesanan.jasper";
            Connection conn = getConnection();

            net.sf.jasperreports.engine.JasperPrint jp
                    = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportPath, null, conn);

            net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);

        } catch (JRException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal mencetak laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_bcetak2ActionPerformed

    private void tampilData1() {
        // Membuat koneksi EntityManager dari persistence unit
        EntityManager em = Persistence.createEntityManagerFactory("Pertemuan12PU").createEntityManager();
        try {
            Query q = em.createNamedQuery("Menu.findByIdMenu");
            List<Menu> hasil = q.getResultList();

            // Membuat model tabel baru dengan kolom yang tidak bisa diedit
            DefaultTableModel model = new DefaultTableModel(new String[]{"ID Menu", "Nama Menu", "Harga", "Kategori"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // semua kolom tidak bisa diedit langsung
                }
            };
           
            for (Menu data : hasil) {
                Object[] baris = new Object[5];
                baris[0] = data.getIdMenu();
                baris[1] = data.getNamaMenu();
                baris[2] = data.getHarga();
                baris[3] = data.getKategori();
                model.addRow(baris);
            }
            
            jtab1.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        } finally {
            em.close(); 
        }
    }

    private void tampilData2() {
        EntityManager em = Persistence.createEntityManagerFactory("Pertemuan12PU").createEntityManager();

        try {
            // Ambil semua data Pesanan, urut berdasarkan ID
            List<Pesanan> hasil = em.createNamedQuery("Pesanan.findAll", Pesanan.class)
                    .getResultList();

            DefaultTableModel model = new DefaultTableModel(
                    new String[]{"ID Pesanan", "Nama Pelanggan", "Jumlah Pesanan", "ID Menu"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            for (Pesanan data : hasil) {
                Object[] baris = new Object[4];
                baris[0] = data.getIdPesanan();
                baris[1] = data.getNamaPelanggan();
                baris[2] = data.getJumlah();
                // Tampilkan ID Menu, bisa juga ganti getNamaMenu() jika ingin nama
                baris[3] = data.getIdMenu() != null ? data.getIdMenu().getIdMenu() : "-";
                model.addRow(baris);
            }

            jtab2.setModel(model);
            jtab2.revalidate();
            jtab2.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        } finally {
            em.close();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DeleteDialog;
    private javax.swing.JDialog DeleteDialog1;
    private javax.swing.JDialog InsertDialog;
    private javax.swing.JDialog InsertDialog1;
    private javax.swing.JDialog UpdateDialog;
    private javax.swing.JDialog UpdateDialog1;
    private javax.swing.JButton bcetak1;
    private javax.swing.JButton bcetak2;
    private javax.swing.JButton bdelete1;
    private javax.swing.JButton bdelete2;
    private javax.swing.JButton binsert1;
    private javax.swing.JButton binsert2;
    private javax.swing.JButton bupdate1;
    private javax.swing.JButton bupdate2;
    private javax.swing.JButton bupload1;
    private javax.swing.JButton bupload2;
    private javax.swing.JComboBox<String> cbka;
    private javax.swing.JComboBox<String> cbka1;
    private javax.swing.JComboBox<String> cbka2;
    private javax.swing.JButton dsubmit1;
    private javax.swing.JButton dsubmt;
    private javax.swing.JButton dtidak;
    private javax.swing.JButton dtidak1;
    private javax.swing.JButton dupdate;
    private javax.swing.JButton dupdate1;
    private javax.swing.JButton dya;
    private javax.swing.JButton dya1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtab1;
    private javax.swing.JTable jtab2;
    private javax.swing.JTextField tha;
    private javax.swing.JTextField tha1;
    private javax.swing.JTextField tha2;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tid1;
    private javax.swing.JTextField tid2;
    private javax.swing.JTextField tid3;
    private javax.swing.JTextField tid4;
    private javax.swing.JTextField tid5;
    private javax.swing.JTextField tjumlah3;
    private javax.swing.JTextField tjumlah4;
    private javax.swing.JTextField tjumlah5;
    private javax.swing.JTextField tmen3;
    private javax.swing.JTextField tmen4;
    private javax.swing.JTextField tmen5;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnama1;
    private javax.swing.JTextField tnama2;
    private javax.swing.JTextField tnama3;
    private javax.swing.JTextField tnama4;
    private javax.swing.JTextField tnama5;
    // End of variables declaration//GEN-END:variables
}
